-- 04_queries.sql
-- Demonstration queries for the Car Rental Management System

-- Query 1: Shows rental history with customer and car information.
SELECT
    r.rental_id,
    c.full_name AS customer_name,
    car.brand,
    car.model,
    r.start_date,
    r.end_date,
    r.status,
    r.total_amount
FROM rentals r
JOIN customers c ON r.customer_id = c.customer_id
JOIN cars car ON r.car_id = car.car_id
ORDER BY r.rental_id;

-- Query 2: Shows all cars currently available for rent.
SELECT
    car_id,
    plate_number,
    brand,
    model,
    year,
    status
FROM cars
WHERE status = 'Available'
ORDER BY brand, model;

-- Query 3: Calculates total revenue per month.
SELECT
    DATE_TRUNC('month', payment_date) AS month,
    SUM(amount) AS total_revenue
FROM payments
GROUP BY DATE_TRUNC('month', payment_date)
ORDER BY month;

-- Query 4: Identifies the top 10 customers based on total rental spending.
SELECT
    c.customer_id,
    c.full_name,
    COUNT(r.rental_id) AS total_rentals,
    SUM(p.amount) AS total_spent
FROM customers c
JOIN rentals r ON c.customer_id = r.customer_id
JOIN payments p ON r.rental_id = p.rental_id
GROUP BY c.customer_id, c.full_name
ORDER BY total_spent DESC
LIMIT 10;

-- Query 5: Shows which cars are rented most frequently.
SELECT
    car.car_id,
    car.brand,
    car.model,
    COUNT(r.rental_id) AS times_rented
FROM cars car
JOIN rentals r ON car.car_id = r.car_id
GROUP BY car.car_id, car.brand, car.model
ORDER BY times_rented DESC
LIMIT 10;

-- Query 6: Calculates revenue generated by each car category.
SELECT
    cc.category_name,
    SUM(p.amount) AS total_revenue
FROM payments p
JOIN rentals r ON p.rental_id = r.rental_id
JOIN cars car ON r.car_id = car.car_id
JOIN car_categories cc ON car.category_id = cc.category_id
GROUP BY cc.category_name
ORDER BY total_revenue DESC;

-- Query 7: Demonstrates the many-to-many relationship between cars and features.
SELECT
    car.brand,
    car.model,
    STRING_AGG(f.feature_name, ', ') AS features
FROM cars car
JOIN car_features cf ON car.car_id = cf.car_id
JOIN features f ON cf.feature_id = f.feature_id
GROUP BY car.brand, car.model
ORDER BY car.brand, car.model;

-- Query 8: Demonstrates the self-referencing employee-manager relationship.
SELECT
    e.full_name AS employee_name,
    e.position,
    m.full_name AS manager_name
FROM employees e
LEFT JOIN employees m ON e.manager_id = m.employee_id
ORDER BY employee_name;

-- Query 9: Uses a CTE to find customers with more than five rentals.
WITH customer_rental_counts AS (
    SELECT
        c.customer_id,
        c.full_name,
        COUNT(r.rental_id) AS rental_count
    FROM customers c
    JOIN rentals r ON c.customer_id = r.customer_id
    GROUP BY c.customer_id, c.full_name
)
SELECT *
FROM customer_rental_counts
WHERE rental_count > 5
ORDER BY rental_count DESC;

-- Query 10: Uses a window function to rank customers by total spending.
SELECT
    c.full_name,
    SUM(p.amount) AS total_spent,
    RANK() OVER (ORDER BY SUM(p.amount) DESC) AS spending_rank
FROM customers c
JOIN rentals r ON c.customer_id = r.customer_id
JOIN payments p ON r.rental_id = p.rental_id
GROUP BY c.full_name
ORDER BY spending_rank;

-- Query 11: Uses a subquery to find cars earning more than the average car revenue.
SELECT
    car.car_id,
    car.brand,
    car.model,
    SUM(p.amount) AS car_revenue
FROM cars car
JOIN rentals r ON car.car_id = r.car_id
JOIN payments p ON r.rental_id = p.rental_id
GROUP BY car.car_id, car.brand, car.model
HAVING SUM(p.amount) > (
    SELECT AVG(car_total)
    FROM (
        SELECT SUM(p2.amount) AS car_total
        FROM cars car2
        JOIN rentals r2 ON car2.car_id = r2.car_id
        JOIN payments p2 ON r2.rental_id = p2.rental_id
        GROUP BY car2.car_id
    ) AS revenue_per_car
)
ORDER BY car_revenue DESC;

-- Query 12: Calculates total maintenance cost for each car.
SELECT
    car.brand,
    car.model,
    COUNT(m.maintenance_id) AS maintenance_count,
    SUM(m.cost) AS total_maintenance_cost
FROM cars car
JOIN maintenance m ON car.car_id = m.car_id
GROUP BY car.brand, car.model
ORDER BY total_maintenance_cost DESC;
